### PR TITLE
Fix broken url to "Better Bloom Filter" paper

### PR DESCRIPTION
**Pull request by andrelaszlo**
I noticed that this link was broken so I replaced it with a link to a copy provided by the other author

### CODE REVIEW

**Comment by fuerve** [comment]
Thanks for that.  I haven't looked at this in ages, glad I stopped by!

**Comment by andrelaszlo** [comment]
Cool repo! Just out of curiosity - how often do you interview? :)

**Comment by fuerve** [comment]
Not very often, but for whatever reason, I get serious nerves during interviews.  It's a lifelong character flaw.  The wheels just tend to fall off of whiteboard interviews, whenever I do them.  It's silly, of course: at this stage of my career, I've been the interviewer a far greater number of times than the interviewee, but it still shakes me to stand in front of that whiteboard.

**Comment by andrelaszlo** [comment]
@fuerve I get that. I have done very few whiteboard interviews - and the ones I've done have been an okay experience - but I never feel prepared enough.

**Pull request merged**
